### NUMPY->PLAY WITH ARRAYS(NUMBER)
### PANDAS->DATASET
### MATPLOTLIB->DATA VISUALIZATION
### SEABORN->DATA VISUALIZATION
### SCIPY->STATISTICAL









## NUMPY->PLAY WITH ARRAYS(NUMBER)


In [1]:
import numpy as np

In [2]:
simple_list=[6,7,8]
np.array(simple_list)

array([6, 7, 8])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(5,25)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [7]:
np.arange(1,99)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [8]:
np.arange(6,78542)

array([    6,     7,     8, ..., 78539, 78540, 78541])

In [9]:
np.arange(1,36,5)    ### shift+tab for hrlp 

array([ 1,  6, 11, 16, 21, 26, 31])

In [10]:
np.arange(5,99,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
       56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [11]:
np.arange(0,785,125)

array([  0, 125, 250, 375, 500, 625, 750])

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(85)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84])

In [14]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(52)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [18]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [22]:
np.ones((2,3),int )

array([[1, 1, 1],
       [1, 1, 1]])

In [21]:
np.ones((5,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
np.linspace(0,2,40)

array([0.        , 0.05128205, 0.1025641 , 0.15384615, 0.20512821,
       0.25641026, 0.30769231, 0.35897436, 0.41025641, 0.46153846,
       0.51282051, 0.56410256, 0.61538462, 0.66666667, 0.71794872,
       0.76923077, 0.82051282, 0.87179487, 0.92307692, 0.97435897,
       1.02564103, 1.07692308, 1.12820513, 1.17948718, 1.23076923,
       1.28205128, 1.33333333, 1.38461538, 1.43589744, 1.48717949,
       1.53846154, 1.58974359, 1.64102564, 1.69230769, 1.74358974,
       1.79487179, 1.84615385, 1.8974359 , 1.94871795, 2.        ])

In [28]:
np.linspace(1,999,50)

array([  1.        ,  21.36734694,  41.73469388,  62.10204082,
        82.46938776, 102.83673469, 123.20408163, 143.57142857,
       163.93877551, 184.30612245, 204.67346939, 225.04081633,
       245.40816327, 265.7755102 , 286.14285714, 306.51020408,
       326.87755102, 347.24489796, 367.6122449 , 387.97959184,
       408.34693878, 428.71428571, 449.08163265, 469.44897959,
       489.81632653, 510.18367347, 530.55102041, 550.91836735,
       571.28571429, 591.65306122, 612.02040816, 632.3877551 ,
       652.75510204, 673.12244898, 693.48979592, 713.85714286,
       734.2244898 , 754.59183673, 774.95918367, 795.32653061,
       815.69387755, 836.06122449, 856.42857143, 876.79591837,
       897.16326531, 917.53061224, 937.89795918, 958.26530612,
       978.63265306, 999.        ])

In [29]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [30]:
np.random.randn(2,4)
arr

array([1, 2, 3])

In [31]:
np.random.randn(3,5)

array([[ 0.02778641,  0.25136222, -1.60120099,  1.1828846 , -0.94109397],
       [ 0.54261808, -0.73422035,  0.85416065,  1.38504548, -0.60063468],
       [-0.04190009,  0.37104229,  0.37555305, -1.9393993 ,  0.31718199]])

In [38]:
np.random.randint(2,100)

63

In [36]:
np.random.randint(20,56,100)

array([50, 47, 33, 54, 21, 27, 54, 50, 39, 31, 41, 36, 24, 55, 21, 20, 49,
       39, 50, 35, 28, 33, 21, 20, 47, 26, 20, 37, 26, 22, 41, 52, 20, 53,
       35, 24, 22, 41, 29, 32, 52, 54, 53, 30, 45, 40, 48, 35, 55, 44, 42,
       27, 53, 48, 54, 42, 47, 21, 45, 22, 51, 47, 49, 25, 26, 52, 51, 33,
       41, 28, 36, 21, 28, 55, 48, 37, 21, 53, 31, 23, 27, 40, 45, 36, 55,
       51, 32, 33, 32, 32, 54, 39, 42, 47, 42, 32, 22, 26, 28, 53])

In [34]:
array=np.arange(30)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [40]:
array=np.random.randint(0,10,50)
array

array([4, 8, 7, 5, 6, 2, 8, 2, 8, 0, 2, 1, 1, 6, 2, 6, 4, 5, 9, 1, 8, 7,
       1, 4, 7, 4, 7, 2, 8, 2, 9, 1, 1, 5, 4, 9, 2, 2, 1, 0, 7, 9, 1, 3,
       7, 2, 4, 7, 6, 7])

In [43]:
array.reshape(5,10)

array([[4, 8, 7, 5, 6, 2, 8, 2, 8, 0],
       [2, 1, 1, 6, 2, 6, 4, 5, 9, 1],
       [8, 7, 1, 4, 7, 4, 7, 2, 8, 2],
       [9, 1, 1, 5, 4, 9, 2, 2, 1, 0],
       [7, 9, 1, 3, 7, 2, 4, 7, 6, 7]])